import { AppShell } from "@/components/layout/app-shell";
import { StatCard } from "@/components/ui/stat-card";
const metrics=[{label:"Net P&L",value:"$0.00",detail:"Your recorded trades will appear here"},{label:"Win rate",value:"—",detail:"Calculated from closed trades"},{label:"Trades logged",value:"0",detail:"Manual entries and imports"},{label:"Avg. R multiple",value:"—",detail:"Available when risk data is recorded"}];
export default function DashboardPage(){return <AppShell active="Overview">
<section className="page-heading"><div><p className="eyebrow">YOUR WORKSPACE</p><h1>Trading overview</h1><p className="muted">A clear record of your decisions, one trade at a time.</p></div><span className="status-pill"><span className="status-dot"/>Foundation mode</span></section>
<section className="stats-grid" aria-label="Trading performance summary">{metrics.map(metric=><StatCard key={metric.label} {...metric}/>)}</section>
<section className="content-grid"><div className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">RECORDS</p><h2>Recent trades</h2></div><span className="muted small">0 records</span></div><div className="empty-state"><div className="empty-icon" aria-hidden="true">↗</div><h3>Your trading history starts here</h3><p>When trade entry is connected to your private database, your latest trades will appear here.</p><span className="secondary-button" aria-disabled="true">Trade entry · planned</span></div></div>
<aside className="panel next-panel"><p className="eyebrow">BUILT FOR REVIEW</p><h2>Process over impulse.</h2><p className="muted">Capture the setup, risk, execution, and lesson behind each trade—not just the result.</p><ul className="feature-list"><li><span>01</span><div><strong>Record</strong><p>Manual trades first</p></div></li><li><span>02</span><div><strong>Reflect</strong><p>Notes, tags, and screenshots</p></div></li><li><span>03</span><div><strong>Improve</strong><p>Metrics derived from your records</p></div></li></ul></aside></section>
<p className="footnote">Preview scaffold · No real account data is connected yet.</p></AppShell>}
